<?php

namespace App\Http\Requests;

use App\Models\Kategori;
use App\Models\Status;
use Illuminate\Foundation\Http\FormRequest;

class ProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'nama_produk'=>'required|string|max:255',
            'harga'=>'required|integer|min:0',
            'kategori_id'=>['required','integer',function ($attribute, $value, $fail) {
                $kategori = Kategori::query()->firstWhere('id_kategori',$value);
                    if (!$kategori){
                        $fail('Kategori tidak ditemukan');
                    }
            }],
            'status_id'=>['required','integer',function ($attribute, $value, $fail) {
                $status = Status::query()->firstWhere('id_status',$value);
                if (!$status){
                    $fail('Status tidak ditemukan');
                }
            }],
        ];
    }

    public function messages():array
    {
        return [
            'required'=>':attribute harus diisi',
            'string'=>':attribute harus berupa string',
            'max'=>':attribute maksimal :max karakter',
            'integer'=>':attribute harus berupa angka',
            'min'=>':attribute minimal :min',
        ]; // TODO: Change the autogenerated stub
    }
}
